GET http://localhost:3000/users

###

GET http://localhost:3000/users?limit=2&offset=2

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5"
}

###

PATCH http://localhost:3000/users/fc3f210e-0562-4327-843e-7e205f29fcda
Content-Type: application/json

{
  "address": "서울특별시 강남구 무실로 234번길 45-6"
}

###

DELETE http://localhost:3000/users/fc3f210e-0562-4327-843e-7e205f29fcda


###
GET http://localhost:3000/users/6c3a18b0-11c5-4d97-9019-9ebe3c4d1317/saved-products